mudisk/extract changed

diff --git a/extract b/extract
--- a/extract
+++ b/extract
@@ -1,24 +1,29 @@
 #!/usr/bin/env bash
 
-# Extract archives - use: extract <file>
-# Credits to http://dotfiles.org/~pseup/.bashrc
-
-if [ -f $1 ]; then
-    case $1 in
-        *.tar.bz2)  tar xjf $1   ;;
-        *.tar.gz)   tar xzf $1   ;;
-        *.tar.xz)   tar Jxf $1   ;;
-        *.bz2)      bunzip2 $1   ;;
-        *.rar)      unrar x $1   ;;
-        *.gz)       gunzip $1    ;;
-        *.tar)      tar xf $1    ;;
-        *.tbz2)     tar xjf $1   ;;
-        *.tgz)      tar xzf $1   ;;
-        *.zip)      unzip $1     ;;
-        *.Z)        uncompress $1;;
-        *.7z)       7z x $1      ;;
-        *)          echo "'$1' cannot be extracted via zx()" ;;
-    esac
-else
+if [ ! -f $1 ]; then
     echo "'$1' is not a valid file"
+    exit 1
 fi
+
+case $1 in
+    *.tar.bz2)  tar xjf $1   ;;
+    *.tar.gz)   tar xzf $1   ;;
+    *.tar.xz)   tar Jxf $1   ;;
+    *.bz2)      bunzip2 $1   ;;
+    *.rar)      unrar x $1   ;;
+    *.gz)       gunzip $1    ;;
+    *.tar)      tar xf $1    ;;
+    *.tbz2)     tar xjf $1   ;;
+    *.tgz)      tar xzf $1   ;;
+    *.zip)      unzip $1     ;;
+    *.Z)        uncompress $1;;
+    *.7z)
+        7z t -pnull $1
+        if [ $? -eq 0 ]; then
+            7z x $1
+        else
+            echo "The file is password protected!"
+        fi
+        ;;
+    *)  echo "'$1' cannot be extracted!" ;;
+esac
