vifmmed changed

diff --git a/vifmmed b/vifmmed
--- a/vifmmed
+++ b/vifmmed
@@ -7,7 +7,7 @@
 #  - unmount <path> -- unmount given mount point
 
 function help() {
-    echo "Usage: vifm-media list | mount <device> | unmount <path>"
+    echo "Usage: vifm-media list | mount <device> | unmount/eject <path>"
     exit 1
 }
 
@@ -42,6 +42,7 @@ function list() {
     done <<< "$("$monitor" --enumerate-device-files)"
 }
 
+# we can also use "udisksctl info/mount/unmount", but need to re-write list function.
 if type -P devmon udevil &>/dev/null; then
     monitor=devmon
 
@@ -56,23 +57,12 @@ if type -P devmon udevil &>/dev/null; then
     function unmount() {
         devmon --unmount "$1"
     }
-elif type -P udisksctl &>/dev/null; then
-    monitor=udisksctl
 
-    function info() {
-        udisksctl info -b "$@"
-    }
-
-    function mount() {
-        udisksctl mount "$1"
-    }
-
-    function unmount() {
-        udisksctl unmount "$1"
+    function eject() {
+        devmon --eject "$1"
     }
 else
-    echo "Neither of the supported backends were found" \
-         "(udevil, udisksctl)" >&2
+    echo "(devmon, udevil) not found!" >&2
     exit 1
 fi
 
@@ -81,6 +71,7 @@ case "$1" in
         if [ $# -ne 1 ]; then
             help
         fi
+
         list
         #lsblk -no NAME,LABEL,MOUNTPOINT | sed 's/\s\+/:/'
         ;;
@@ -89,6 +80,7 @@ case "$1" in
         if [ $# -ne 2 ]; then
             help
         fi
+
         mount "$2"
         #sudo mount -t auto -o noatime,nodev,nosuid "$2"
         ;;
@@ -97,8 +89,18 @@ case "$1" in
         if [ $# -ne 2 ]; then
             help
         fi
+
         unmount "$2"
         #sudo umount "$2"
+        ;;
+
+    eject)
+        if [ $# -ne 2 ]; then
+            help
+        fi
+
+        eject "$2"
+        #sudo eject "$2"
         ;;
 
     *)
